[package]
name = "Soul_lang_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
num-traits = "0.2.19"
regex = "1.11.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
