[package]
name = "hsoul"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
ego-tree = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }